### ISSUE TITLE
REPEATER isn't working?

### ISSUE THREAD

**Issue by antonio-emilio** [things4u/ESP-1ch-Gateway#40]
I've been using this project for the last few days and it helped me alot. 
I was needing something to do like a "Mesh" network, using the ESP32 to receive a package and then send it again to the gateway.
This code has an "REPEATER" option, but It seens like it doesnt do nothing... am I correct?

**Comment by platenspeler** [comment]
Yes you are correct.
 I am still working on this idea but since there was no interest I have not yet implemented  nor tested its functionality 100%.

Maarten

Verstuurd vanaf mijn iPad

Op 13 jul. 2020 om 13:35 heeft Antonio Emilio <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I've been using this project for the last few days and it helped me alot.
I was needing something to do like a "Mesh" network, using the ESP32 to receive a package and then send it again to the gateway.
This code has an "REPEATER" option, but It seens like it doesnt do nothing... am I correct?

**Comment by antonio-emilio** [comment]
> Yes you are correct. I am still working on this idea but since there was no interest I have not yet implemented nor tested its functionality 100%. Maarten Verstuurd vanaf mijn iPad Op 13 jul. 2020 om 13:35 heeft Antonio Emilio <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven: I've been using this project for the last few days and it helped me alot. I was needing something to do like a "Mesh" network, using the ESP32 to receive a package and then send it again to the gateway. This code has an "REPEATER" option, but It seens like it doesnt do nothing... am I correct? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthings4u%2FESP-1ch-Gateway%2Fissues%2F40&data=02%7C01%7C%7C6b077c4f20b94c3bdaa908d82720dce8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637302369376785295&sdata=f7oCfeLubF505Bhiya7Vj34MVwDyimSAMx9o9Xn%2FIl0%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABMSRHGP3XKM3T4NZBV7G5LR3LWQRANCNFSM4OYMQGZQ&data=02%7C01%7C%7C6b077c4f20b94c3bdaa908d82720dce8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637302369376795282&sdata=CPNYkONs2q0O8%2B3BXsfbiVEKtE1rH0ue01wmYuC6hwM%3D&reserved=0>.

I got it. I made some adaptations, integrating another code with this one and it worked. 
I think it would be a good feature...

**Comment by AllTracking** [comment]
@antonio-emilio  Could you share the modified code?

@platenspeler thank you for such a library but why in the repeater mode it still requires the SSID(even when i set the _LOCALSERVER=0)? i would like to test the Repeater functionality in a place where no wifi signal or ethernet exists.
